/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.learning;

import com.learning.ioc.SimpleIoCContainer;
import com.learning.main.Business;
import com.learning.service.GreetingService;
import com.learning.service.impl.GreetingServeiceImpl;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    public Business business;
    @BeforeEach
    public void setUp() {
        SimpleIoCContainer container = new SimpleIoCContainer();
        container.register(GreetingService.class, GreetingServeiceImpl.class);

        business = container.resolve(Business.class);
    }


    @Test void appHasAGreeting() {
        Assertions.assertEquals("Hello, World", business.run("World"));
        Assertions.assertEquals("Hello, Home", business.run("Home"));
    }
}
